"use client";

import React, { useState } from "react";

const FAQs = () => {
  const [faqs, setFaqs] = useState([
    {
      id: 1,
      question: "What is the purpose of the PDF to quiz converter?",
      answer:
        "The purpose of the PDF to quiz converter is to streamline the process of converting educational materials in PDF format into interactive quizzes that can be used for learning and assessment purposes.",
    },
    {
      id: 2,
      question: "How does the PDF to quiz converter work?",
      answer:
        "The PDF to quiz converter uses algorithms to analyze the content of PDF documents, extract relevant information, and generate quiz questions based on the extracted content. Users can upload PDF files, and the converter will parse the text, identify key concepts, and generate appropriate quiz questions.",
    },
    {
      id: 3,
      question: "What types of quizzes can be generated?",
      answer:
        "The PDF to quiz converter can generate various types of quizzes, including multiple-choice questions, true/false questions, fill-in-the-blank questions, and short answer questions, depending on the content of the PDF document.",
    },
    {
      id: 4,
      question: "Can users customize the quizzes generated by the converter?",
      answer:
        "Yes, users have the option to customize the quizzes generated by the converter. They can choose the number of questions, select specific topics or sections from the PDF document, and adjust the difficulty level of the questions.",
    },
    {
      id: 5,
      question:
        "How does the AI teaching assistant enhance the learning experience?",
      answer:
        "The AI teaching assistant analyzes user interactions with the quizzes, identifies learning patterns, and provides personalized feedback and recommendations to help users improve their understanding of the material. It offers explanations for incorrect answers, suggests additional study materials, and adapts the learning experience to suit individual learning styles.",
    },
    {
      id: 6,
      question: "Is the AI teaching assistant capable of answering questions?",
      answer:
        "While the AI teaching assistant primarily focuses on providing feedback and recommendations based on user interactions with the quizzes, it can also answer basic questions related to the content of the quizzes and provide additional explanations as needed.",
    },
    {
      id: 7,
      question:
        "How is user data protected and secured within the application?",
      answer:
        "User data is encrypted and stored securely within the application. We employ industry-standard security measures to protect user privacy and ensure that sensitive information remains confidential.",
    },
  ]);

  const toggleAnswer = (id) => {
    const updatedFaqs = faqs.map((faq) => {
      if (faq.id === id) {
        faq.isOpen = !faq.isOpen;
      }
      return faq;
    });
    setFaqs(updatedFaqs);
  };

  return (
    <div className="bg-gradient-to-r from-rose-100 to-teal-100 min-h-screen py-8">
      <div className="container mx-auto px-4">
        <h1 className="text-3xl font-bold text-center text-gray-800 mb-8">
          Frequently Asked Questions (FAQs)
        </h1>

        {faqs.map((faq) => (
          <div
            key={faq.id}
            className="bg-white rounded-lg shadow-md overflow-hidden mb-4"
          >
            <div
              className="flex justify-between items-center px-4 py-3 border-b border-gray-200 cursor-pointer"
              onClick={() => toggleAnswer(faq.id)}
            >
              <h2 className="text-lg font-semibold text-gray-800">
                {faq.question}
              </h2>
              <div className="text-gray-600">{faq.isOpen ? "✕" : "+"}</div>
            </div>
            {faq.isOpen && (
              <div className="px-4 py-3 text-gray-700">{faq.answer}</div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default FAQs;
